### ISSUE TITLE
Rename as we can use this for more than just sormas-repo

### ISSUE THREAD

**Issue by JonasCir** [healthIMIS/ci-analyzer#3]
ci-time-analyzer maybe?

**Comment by DavidBaldsiefen** [comment]
Yea I thought about this too. CI-time-analyzer sounds nice :) But please note that the current code is super WIP and not exactly clean. I can fix it up a little bit in my freetime though :)

**Comment by JonasCir** [comment]
Yeah sure no pressure! :) Just a general remark :D
